version: '2'
services:
  mongo:
    image: mongo
    hostname: mongo
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - mongodb_data:/data/db
  feathers:
    image: aamservices/feathersjs:puppeteer
    restart: unless-stopped
    volumes:
      - feathers_data:/usr/src/app
    networks:
      - internal
    ports:
      - 1337
    depends_on:
      - mongo
volumes:
  mongodb_data:
    driver: local
  sails_data:
    driver: local
